### ISSUE TITLE
Update Prometheus configuration to allow insecure tls

### ISSUE THREAD

**Issue by mzeevi** [dana-team/hns#67]
The `monitor.yaml` is wrong and non-standard.

Should be:

```
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 labels:
   control-plane: controller-manager
 name: controller-manager-metrics-monitor
 namespace: system
spec:
 endpoints:
   - path: /metrics
     port: https
     scheme: https
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     tlsConfig:
       insecureSkipVerify: true
 selector:
   matchLabels:
     control-plane: controller-manager
```

https://github.com/dana-team/hns/blob/61111514b8f24862fc7e638bd9959b508e0c86d0/config/prometheus/monitor.yaml#L2-L16

/kind bug
